// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sign_Up_Form;

#nullable disable

namespace Sign_Up_Form.Migrations
{
    [DbContext(typeof(ShareYourRoutineContext))]
    [Migration("20220909181843_isactivePropertyadditiontousertablesetdefaultvalue")]
    partial class isactivePropertyadditiontousertablesetdefaultvalue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sign_Up_Form.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("MsgId")
                        .HasColumnType("int")
                        .HasColumnName("msgId");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MsgId");

                    b.HasIndex("PostId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Sign_Up_Form.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Sign_Up_Form.Login", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("Sign_Up_Form.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Msg")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("msg");

                    b.Property<int?>("RecieverId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecieverId");

                    b.HasIndex("SenderId");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("Sign_Up_Form.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ack")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("GeneratorTime")
                        .HasColumnType("datetime");

                    b.Property<int>("GeneratorUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<bool>("Opened")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneratorUserId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Sign_Up_Form.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("NoOfComments")
                        .HasColumnType("int");

                    b.Property<int>("NoOfLikes")
                        .HasColumnType("int");

                    b.Property<string>("PostCategory")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PostMessage")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("Sign_Up_Form.UserDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("About")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("firstName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("Sign_Up_Form.Comment", b =>
                {
                    b.HasOne("Sign_Up_Form.Message", "Msg")
                        .WithMany("Comments")
                        .HasForeignKey("MsgId")
                        .IsRequired()
                        .HasConstraintName("FK_Comment_ToTable");

                    b.HasOne("Sign_Up_Form.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Comment_ToTable_1");

                    b.Navigation("Msg");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Sign_Up_Form.Like", b =>
                {
                    b.HasOne("Sign_Up_Form.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Table_ToTableofLike");

                    b.HasOne("Sign_Up_Form.UserDatum", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Table_ToTableofLike1");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sign_Up_Form.Login", b =>
                {
                    b.HasOne("Sign_Up_Form.UserDatum", "IdNavigation")
                        .WithOne("Login")
                        .HasForeignKey("Sign_Up_Form.Login", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Login_ToTable");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Sign_Up_Form.Message", b =>
                {
                    b.HasOne("Sign_Up_Form.Login", "Reciever")
                        .WithMany("MessageRecievers")
                        .HasForeignKey("RecieverId")
                        .HasConstraintName("FK_message_ToTable_1");

                    b.HasOne("Sign_Up_Form.Login", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_message_ToTable");

                    b.Navigation("Reciever");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Sign_Up_Form.Notification", b =>
                {
                    b.HasOne("Sign_Up_Form.Login", "GeneratorUser")
                        .WithMany("NotificationGeneratorUsers")
                        .HasForeignKey("GeneratorUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_ToTable_2");

                    b.HasOne("Sign_Up_Form.Post", "Post")
                        .WithMany("Notifications")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_ToTable");

                    b.HasOne("Sign_Up_Form.Login", "User")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_ToTable_1");

                    b.Navigation("GeneratorUser");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sign_Up_Form.Login", b =>
                {
                    b.Navigation("MessageRecievers");

                    b.Navigation("MessageSenders");

                    b.Navigation("NotificationGeneratorUsers");

                    b.Navigation("NotificationUsers");
                });

            modelBuilder.Entity("Sign_Up_Form.Message", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Sign_Up_Form.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Sign_Up_Form.UserDatum", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Login")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
